### ISSUE TITLE
Websocket 5.0.*

### ISSUE THREAD

**Issue by Mindgamesnl** [andreykaipov/goobs#32] opened 2022-07-19 01:02 UTC
Hey there,

I've noticed that there's a 5.0 branch that's been untouched since February.
Are there any plans to update this project to support 5.0, or is it considered dead/unmaintained?

**Comment by andreykaipov** [comment] 2022-07-19 03:19
Hey thanks for checking this project out. Regarding v5 - I left a comment on the upstream CLI that consumes this library at https://github.com/muesli/obs-cli/discussions/55#discussioncomment-2527385.

The problem is the v5 generated protocol isn't as complete as v4, which forces me to manually maintain the structs for each request and event, instead of generating it from their protocol.json file. Problematic request and event types can be found by `ctrl+f`'ing for `"valueType": "Object"` or `"valueType": "Array<Object>"` in this file https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.json. Alternatively I can just map `Object` types to a generic `map[string]interface{}`, but that's kinda annoying to use in practice.

To answer your question though -- no it's not dead, I still have plans to maintain this. I was just really hoping to avoid testing all the v5 endpoints to figure out how the `Object` types look to figure out how to write the structs. In the linked comment I mentioned waiting till the official v5 release to see if the protocol updates those `Object` types, but with the release happening [two weeks ago](https://github.com/obsproject/obs-websocket/releases/tag/5.0.0), I suppose I have my answer. 😅

I've been swamped with a lot of personal head clutter and work things going on, so not sure how soon I can promise to get a v5 compatible client out. Knowing the way forward though, I'll try to make some progress soon. :)

**Comment by andreykaipov** [comment] 2022-08-11 04:56
Hi @Mindgamesnl, I was able to get a release out for v5! The object mapping stuff wasn't as bad as I thought it'd be.

I'm gonna close this issue but feel free to lemme know if you run into anything whenever you try it out.

**Closed by andreykaipov** 2022-08-11 04:56 UTC
