### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Vany** [andreykaipov/goobs#58] opened 2023-10-04 15:04 UTC
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100c7234c]

goroutine 37 [running]:
github.com/andreykaipov/goobs.(*Client).Disconnect(0x0)
	/Users/vany/go/pkg/mod/github.com/andreykaipov/goobs@v0.12.1/client.go:89 +0x1c
github.com/vany/controlrake/src/obs.(*Obs).Init.func1()
	/Users/vany/a/controlrake/src/obs/obs.go:61 +0x12c
created by github.com/vany/controlrake/src/obs.(*Obs).Init in goroutine 1
	/Users/vany/a/controlrake/src/obs/obs.go:45 +0xe0
	
	
	it is after obs was shuted down i called disconnect()

**Comment by afriza** [comment] 2023-10-07 11:05
@Vany in my opinion, it seems to be some logic issue in your application. `o.Client` is `nil` when you call `o.Client.Disconnect()`.

**Comment by andreykaipov** [comment] 2023-11-05 22:38
Hey @Vany, sorry for the late reply but unfortunately I can't reproduce this by disconnecting after OBS is already shut down.

The stack trace is interesting though. It's indicating [this](https://github.com/andreykaipov/goobs/blob/v0.12.1/client.go#L89) is the problem line. So either `c.Client.Log` or `c.Client` is nil, but this should be impossible if called after `goobs.New()` because that's all initialized [here](https://github.com/andreykaipov/goobs/blob/v0.12.1/client.go#L102-L125).

Like @afriza mentioned, I think you've got something strange happening in your initialization code there. Could you provide a minimal reproducible example?

**Comment by andreykaipov** [comment] 2023-12-21 17:33
I'm gonna close this out. I saw in the latest version of your code you have a nil check. I think that's a good way to go about it. I released a new major version v1.0.0 that includes some improvements to the disconnection logic as well as hiding any internal fields to make troubleshooting things like this easier in the future.

**Closed by andreykaipov** 2023-12-21 17:33 UTC
